### ISSUE TITLE
kounch PR#2 wainting to be merged since 10 may

### ISSUE THREAD

**Issue by ricardodepinho** [stripwax/wav2tzx#3]
Dear Dave, could you please review and if ok, merge the PR#2 by kounch.
https://github.com/stripwax/wav2tzx/pull/2
thank you!

**Comment by stripwax** [comment]
Which particular part is most important for you?  Including documentation that is not part of the original source doesn't really make sense to me, and I cannot test anything on MacOS.  Whereas the fix does seem useful, but my version seems to work ok without that fix.  More testing is required?

It was never my intention to make this a 'living' project in GitHub and I am not the original author;  at best, this is a fork.  But I can try to help you.

**Comment by ricardodepinho** [comment]
Dear Dave. 
Thank you for merging the PR#2.
For me the fix is important and the documentation is also useful for users.
I will try to test the documentation and if I find anything wrong or need to fix, I will add an issue or create a PR myself!
Have a fantastic 2025!
